import axios from 'axios';
import { formatContextForPrompt } from '../utils/calendar.js';

const getEnv = (key) => process.env[key];

const OPENROUTER_API_KEY = () => getEnv('OPENROUTER_API_KEY');
const OPENROUTER_BASE_URL = 'https://openrouter.ai/api/v1';

const QUOTE_SYSTEM_PROMPT = `You are a master poet and theologian specializing in Amharic spiritual content for Ethiopian Orthodox Christians.

Requirements:
- Generate ONE short, breathtakingly poetic sentence in strictly modern AMHARIC language (max 30 words).
- IMPORTANT: Write entirely in the Amharic language. DO NOT write in the ancient Ge'ez language. Use Amharic grammar and vocabulary completely.
- The style must be profound and beautifully composed in professional Ethiopian Orthodox liturgical tone
- DO NOT use clichés or generic phrases; make it deeply resonant with EOTC theology
- Return ONLY the pure Amharic text - NO explanation, NO translations, NO quotation marks.`;

const CAROUSEL_SYSTEM_PROMPT = `You are an expert theologian creating content for Ethiopian Orthodox Christian youth.

Generate a 5-slide carousel about the given spiritual topic. Each slide must have:
1. "title": A short, impactful title (Amharic, 2-5 words)
2. "content": A profound reflection or teaching (Amharic, 15-25 words)
3. "reference": A relevant Bible reference using STRICT Ge'ez numerals (e.g., ማቴዎስ ፭፥፰)

CRITICAL: Bible references must use Ge'ez numerals (፩, ፪, ፫, ፬, ፭, ፮, ፯, ፮, ፱, ፲...).
Return format MUST be a valid JSON array of 5 objects:
[
  {"title": "...", "content": "...", "reference": "..."},
  ...
]
Return ONLY JSON, no markdown formatting or explanations.`;

const VERSE_SYSTEM_PROMPT = `You are an Ethiopian Orthodox biblical scholar. Your task is to provide a PERFECT Bible verse in Amharic based on a given theme.

Instructions:
1. Provide the EXACT literal text from the Haile Selassie 1962 (EOTC) Amharic Bible.
2. DO NOT paraphrase, summarize, or use vague words. Every letter must be accurate.
3. Use ONLY Ge'ez numerals for CHAPTER and VERSE references (e.g., መዝሙር ፳፫፥፩).
4. DO NOT hallucinate. If you are unsure of the literal text, use a common verse you know perfectly (e.g. from Psalms, John, or Matthew).

Provide ONLY a JSON object with:
- "verse": The literal, error-free Amharic text.
- "reference": The book name and ref in Ge'ez numerals (e.g., ማቴዎስ ፭፥፰).

CRITICAL: You MUST include BOTH "verse" and "reference" keys. Failure to do so is unacceptable.
Return ONLY JSON, no markdown.`;

const REFLECTION_SYSTEM_PROMPT = `You are a respected Ethiopian Orthodox priest writing a weekly spiritual reflection.

Requirements:
1. "title": A profound title (Amharic, 2-6 words)
2. "scripture": The EXACT literal Bible verse text (1962 EOTC Version). NO paraphrasing.
3. "reference": The scripture reference using Ge'ez numerals (e.g., ዮሐንስ ፫፥፲፮).
4. "reflection": A deep, multi-paragraph teaching (Amharic, 3-4 paragraphs, profound and traditional).
5. "prayer": A short concluding prayer starting with "አቤቱ አምላካችን..." (Amharic)

CRITICAL: The scripture verse must be letter-perfect.
Return ONLY JSON, no markdown.`;

const AUDITOR_SYSTEM_PROMPT = `You are an elite Ethiopian Orthodox Theological Auditor and "Super-Proofreader". Your ONLY job is to verify and correct Amharic content generated by another AI.

Strict Guidelines:
1. Fix any typos or grammatical mistakes. Ensure the text is perfectly written in the modern AMHARIC language. If the previous AI hallucinated ancient Ge'ez language or strange grammar, rewrite it into beautiful, grammatically correct Amharic.
2. Verify all scriptural references against the literal 1962 EOTC Amharic Bible. If it's paraphrased or slightly wrong, correct it to the exact literal text.
3. ALL NUMBERS in titles, text, and references MUST be converted to strictly Ge'ez numerals (e.g., 1 -> ፩, 2 -> ፪, 10 -> ፲). Look very closely for Arabic numerals (1, 2, 3) and convert them.
4. CRITICAL SPELLING: Ensure all proper nouns and EOTC terms are spelled perfectly in Amharic (e.g., 'Qusquam' or 'Kusquam' MUST always be exactly 'ቁስቋም' NOT 'ቅስቋም' or 'ቅፍቃም').
5. Keep the output strictly in the exact same format as the input. NEVER add markdown (like \`\`\`json) or extra conversational text. Return ONLY the validated content.`;

// ─── Content Topic Pool ────────────────────────────────────────────────────
// 60+ diverse topics spanning theology, ethics, history, spirituality & culture.
// These are used when NO liturgical context is active, ensuring maximum variety.
const THEMES = [
  // ── Core Virtues & Spiritual Dispositions ──
  'ሃይማኖት እና እምነት (Faith and Belief — trusting God in the unseen)',
  'ተስፋ (Hope — the anchor of the soul)',
  'መንፈሳዊ ፍቅር (Unconditional Spiritual Love — Agape)',
  'እውነተኛ ንስሐ (True Repentance — returning to God with a broken heart)',
  'የአእምሮ ሰላም (Inner Peace — the peace that surpasses understanding)',
  'ትዕግሥት (Patience and Long-suffering)',
  'ትሕትና (Humility — the foundation of all virtues)',
  'ምስጋና (Gratitude and Thanksgiving to God)',
  'ቅድስና (Holiness — being set apart for God)',
  'የልብ ንጽሕና (Purity of Heart and Body)',

  // ── Prayer & Fasting Life ──
  'የጾም እና የጸሎት ኃይል (The Power of Fasting and Prayer)',
  'ዘወትር መጸለይ (Unceasing Prayer — praying without ceasing)',
  'የሌሊት ጸሎትና ሱባዔ (Night Vigils and Subaé — seeking God in silence)',
  'ጸሎተ አቡነ ዘበሰማያት (The Lord\'s Prayer — depth and meaning)',
  'የሥውር ጸሎት (Secret Prayer — finding God in the quiet place)',
  'መዝሙር እና ማኅሌት (Mezmur and Mahlet — Praise through spiritual song)',

  // ── Scripture & Theology ──
  'ሕያው የእግዚአብሔር ቃል (The Living Word of God)',
  'ምሥጢረ ሥላሴ (Mystery of the Holy Trinity — Unity and Trinity)',
  'ምሥጢረ ሥጋዌ (Mystery of the Incarnation — God becoming man)',
  'ትንሣኤ ሙታን (Resurrection of the Dead — Christ and our hope)',
  'ድኅነተ ነፍስ (Salvation of the Soul — what it means to be saved)',
  'የእግዚአብሔር ጸጋ (Divine Grace — unmerited divine favor)',
  'የዕለት እንጀራችን (Our Daily Bread — God\'s daily provision)',
  'የመስቀሉ ቤዛነት (Redemption through the Cross — bought at a great price)',
  'ዘለዓለማዊ ሕይወት (Eternal Life — what awaits the faithful)',

  // ── EOTC Sacraments & Church Life ──
  'ምሥጢረ ቁርባን (Holy Communion — Body and Blood of Christ)',
  'ምሥጢረ ጥምቀት (Holy Baptism — being born of water and Spirit)',
  'ምሥጢረ ሜሮን (Holy Chrism — the seal of the Holy Spirit)',
  'ኑዛዜ እና ንስሐ (Confession and Repentance — the medicine of the soul)',
  'ቅድስት ቤተ ክርስቲያን (The Holy Church — body of Christ, pillar of truth)',
  'የሱባዔ ሕይወት (Subaé — the discipline of extended spiritual retreat)',
  'የቤተ ክርስቲያን ሊቃውንት (The Scholars — the EOTC tradition of Qine and theology)',

  // ── Saints, Martyrs & Ethiopian Fathers ──
  'የሰማዕታት ሕይወት (Martyrdom — dying for Christ)',
  'የምናኔ ሕይወት (Monastic Life — the way of the desert fathers)',
  'ቅዱስ ጊዮርጊስ (St. George — courage, faith, and martyrdom)',
  'አቡነ ተክለ ሃይማኖት (Abune Tekle Haymanot — Ethiopian pillar of faith)',
  'ቅዱስ ያሬድ (St. Yared — divine music, chant, and praise)',
  'ቅዱስ ላሊበላ (King Lalibela — faith carved in living rock)',
  'ተሰዓቱ ቅዱሳን (The Nine Saints — spreading the Gospel in Ethiopia)',
  'ቅዱሳት አንስት (Holy Women of the Bible and the EOTC)',
  'ሕፃኑ ቅዱስ ቂርቆስ (St. Kirkos — the unwavering child martyr)',

  // ── Ethiopian Spiritual Heritage ──
  'ታቦተ ጽዮን (The Tabot — Ark of the Covenant and its profound mystery)',
  'የማኅሌት አገልግሎት (Mahlet — the magnificent night chanting of the EOTC)',
  'ደብረ ዳሞ እና ገዳማት (Debre Damo & Monasteries — fortresses of prayer)',
  'የጻድቃን መንገድ (The Path of the Righteous — walking in God\'s ways)',
  'የኢትዮጵያ ቤተ ክርስቲያን ታሪክ (Ethiopian Church History — 2000 years of faith)',
  'የእግዚአብሔር ኪዳን (Divine Covenant — God\'s promises and our response)',

  // ── Family, Community & Ethics ──
  'ክርስቲያናዊ ቤተሰብ (Christian Family — a church in miniature)',
  'ወላጆችን ማክበር (Honoring Parents — fulfilling the commandment)',
  'ይቅርታ እና ምሕረት (Forgiveness and Mercy — releasing the debt)',
  'መንፈሳዊ አንድነት (Spiritual Unity — the bond of peace)',
  'ምጽዋት (Almsgiving and Charity — seeing Christ in the poor)',
  'እውነተኛ ፍርድ (True Justice — God\'s standard of righteousness)',
  'እውነትን መናገር (Speaking Truth — living without deception)',
  'ከቅንዓት መራቅ (Overcoming Envy — cultivating a generous heart)',
  'ትዕቢት እና ትሕትና (Pride vs. Humility — the great spiritual battle)',
  'ሥራ እንደ መንፈሳዊ አገልግሎት (Work as Worship — doing all things to the glory of God)',

  // ── Personal Transformation ──
  'ልብን ለእግዚአብሔር መስጠት (Giving the Heart to God — true transformation)',
  'ከጨለማ ወደ ብርሃን (From Darkness to Light — the journey of grace)',
  'ፈተናን ማሸነፍ (Overcoming Temptation — standing firm in the Spirit)',
  'ኀዘን እና መጽናናት (Grief and Divine Comfort — God is near the brokenhearted)',
  'መንፈሳዊ ፈውስ (Spiritual Healing — restoration of body and soul)',
  'ክርስቲያናዊ ምርጫ (Christian Choices — weighing decisions with eternal consequence)',
  'የዕለት ተዕለት ክርስቲያናዊ ሕይወት (Daily Christian Living — bearing the cross daily)'
];

const MAX_RETRIES = 3;
const RETRY_DELAY = 2000;

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function getRandomTheme() {
  return THEMES[Math.floor(Math.random() * THEMES.length)];
}

async function retryWithBackoff(fn, retries = MAX_RETRIES) {
  for (let i = 0; i < retries; i++) {
    try {
      return await fn();
    } catch (error) {
      if (i === retries - 1) throw error;
      const delay = RETRY_DELAY * Math.pow(2, i);
      console.log(`⏳ Retrying AI call in ${delay}ms... (attempt ${i + 1}/${retries})`);
      await sleep(delay);
    }
  }
}

const PRIMARY_MODEL = 'google/gemini-2.5-flash';
const FALLBACK_MODELS = ['google/gemini-2.0-flash-001', 'anthropic/claude-sonnet-4.6'];

async function callOpenRouter(apiKey, model, systemPrompt, userPrompt, jsonMode) {
  const response = await axios.post(
    `${OPENROUTER_BASE_URL}/chat/completions`,
    {
      model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      max_tokens: jsonMode ? 1500 : 300,
      temperature: 0.7,
      top_p: 0.9,
      response_format: jsonMode ? { type: "json_object" } : undefined
    },
    {
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': 'https://eotc-media-studio.local',
        'X-Title': 'EOTC Media Studio'
      },
      timeout: 60000
    }
  );

  const content = response.data?.choices?.[0]?.message?.content?.trim();
  if (!content) throw new Error('Empty response from AI API');
  
  return content;
}

async function callAI(systemPrompt, userPrompt, jsonMode = false) {
  const apiKey = OPENROUTER_API_KEY();
  if (!apiKey) throw new Error('OPENROUTER_API_KEY not configured');

  const modelId = process.env.AI_MODEL || PRIMARY_MODEL;
  const modelsToTry = [modelId, ...FALLBACK_MODELS.filter(m => m !== modelId)];

  return retryWithBackoff(async () => {
    let lastError = null;
    for (const model of modelsToTry) {
      try {
        console.log(`🧪 Trying model: ${model}`);
        const content = await callOpenRouter(apiKey, model, systemPrompt, userPrompt, jsonMode);
        
        // If it's JSON mode, verify it's valid JSON before returning
        if (jsonMode) {
          try {
            extractJSON(content); // Just to verify it's parseable
            return content;
          } catch (e) {
            console.warn(`⚠️ Model ${model} returned invalid JSON, trying next...`);
            lastError = new Error(`Invalid JSON from ${model}`);
            continue;
          }
        }
        return content;
      } catch (err) {
        lastError = err;
        const status = err.response?.status;
        const msg = err.response?.data?.error?.message || err.message;
        console.error(`❌ Model ${model} failed (${status || 'Err'}): ${msg}`);
        continue;
      }
    }
    throw lastError || new Error('All models failed');
  });
}

async function verifyAndCorrect(data, jsonMode = true) {
  const apiKey = OPENROUTER_API_KEY();
  if (!apiKey) throw new Error('OPENROUTER_API_KEY not configured');

  // We explicitly use gemini-2.0-flash-001 as the auditor for extreme stability
  const auditorModel = 'google/gemini-2.0-flash-001';
  const payload = jsonMode ? JSON.stringify(data, null, 2) : data;
  
  console.log(`\n🔍 Proofreading with Theological Auditor (${auditorModel})...`);
  
  return retryWithBackoff(async () => {
    try {
      const content = await callOpenRouter(apiKey, auditorModel, AUDITOR_SYSTEM_PROMPT, `Please audit and correct the following content according to guidelines:\n\n${payload}`, jsonMode);
      if (jsonMode) {
        return extractJSON(content);
      }
      return content;
    } catch (err) {
      console.error(`⚠️ Auditor failed, falling back to original content. Error: ${err.message}`);
      return data; // Fall back to original data instead of breaking pipeline
    }
  });
}

function extractJSON(text) {
  try {
    // 1. Try to find JSON block in markdown
    let cleanText = text;
    const jsonMatch = text.match(/```json\s*([\s\S]*?)\s*```/) || text.match(/```\s*([\s\S]*?)\s*```/);
    if (jsonMatch) {
      cleanText = jsonMatch[1];
    }

    // 2. Try to find the outermost JSON structure (either { ... } or [ ... ])
    const firstBrace = cleanText.indexOf('{');
    const firstBracket = cleanText.indexOf('[');
    
    // Choose whichever comes first
    let startIdx = -1;
    if (firstBrace !== -1 && firstBracket !== -1) {
      startIdx = Math.min(firstBrace, firstBracket);
    } else if (firstBrace !== -1) {
      startIdx = firstBrace;
    } else if (firstBracket !== -1) {
      startIdx = firstBracket;
    }

    const lastBrace = cleanText.lastIndexOf('}');
    const lastBracket = cleanText.lastIndexOf(']');
    
    // Choose whichever comes last
    let endIdx = -1;
    if (lastBrace !== -1 && lastBracket !== -1) {
      endIdx = Math.max(lastBrace, lastBracket);
    } else if (lastBrace !== -1) {
      endIdx = lastBrace;
    } else if (lastBracket !== -1) {
      endIdx = lastBracket;
    }

    if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
      cleanText = cleanText.substring(startIdx, endIdx + 1);
    }

    return JSON.parse(cleanText.trim());
  } catch (e) {
    console.error('JSON Extraction failed. Text received:', text);
    throw new Error('Invalid JSON format from AI');
  }
}

export async function generateQuote(liturgicalContext = null) {
  const theme = liturgicalContext ? liturgicalContext.event : getRandomTheme();
  const contextPrompt = formatContextForPrompt(liturgicalContext);
  console.log(`🧠 AI Theme selected: ${theme}${liturgicalContext ? ' (Liturgical)' : ''}`);
  const rawContent = await callAI(QUOTE_SYSTEM_PROMPT, `Theme: ${theme}${contextPrompt}`);
  const auditedContent = await verifyAndCorrect(rawContent, false);
  return { text: auditedContent, theme: theme.split(' ')[0], liturgicalEvent: liturgicalContext?.event || null };
}

export async function generateDailyVerse(liturgicalContext = null) {
  const theme = liturgicalContext ? liturgicalContext.event : getRandomTheme();
  const contextPrompt = formatContextForPrompt(liturgicalContext);
  console.log(`🧠 AI Verse Theme: ${theme}${liturgicalContext ? ' (Liturgical)' : ''}`);
  const content = await callAI(VERSE_SYSTEM_PROMPT, `Provide an uplifting verse about: ${theme}${contextPrompt}`, true);
  const rawData = extractJSON(content);
  if (!rawData.verse || !rawData.reference) throw new Error('Missing verse or reference fields');
  
  const auditedData = await verifyAndCorrect(rawData, true);
  return { ...auditedData, liturgicalEvent: liturgicalContext?.event || null };
}

export async function generateCarousel(topic = null, liturgicalContext = null) {
  const theme = liturgicalContext ? liturgicalContext.event : (topic || getRandomTheme());
  const contextPrompt = formatContextForPrompt(liturgicalContext);
  console.log(`🧠 AI Carousel Theme: ${theme}${liturgicalContext ? ' (Liturgical)' : ''}`);
  const content = await callAI(CAROUSEL_SYSTEM_PROMPT, `Generate 5 slides about: ${theme}${contextPrompt}`, true);
  const rawSlides = extractJSON(content);
  
  if (!Array.isArray(rawSlides) || rawSlides.length !== 5) {
    throw new Error(`Expected 5 slides in array, got ${rawSlides.length || 0}`);
  }
  
  const auditedSlides = await verifyAndCorrect(rawSlides, true);
  return { slides: auditedSlides, theme: theme.split(' ')[0], liturgicalEvent: liturgicalContext?.event || null };
}

export async function generateWeeklyReflection(liturgicalContext = null) {
  const theme = liturgicalContext ? liturgicalContext.event : getRandomTheme();
  const contextPrompt = formatContextForPrompt(liturgicalContext);
  console.log(`🧠 AI Reflection Theme: ${theme}${liturgicalContext ? ' (Liturgical)' : ''}`);
  const content = await callAI(REFLECTION_SYSTEM_PROMPT, `Write a deep reflection on: ${theme}${contextPrompt}`, true);
  const rawData = extractJSON(content);
  
  if (!rawData.title || !rawData.reflection || !rawData.prayer) {
    throw new Error('Missing required reflection fields');
  }
  
  const auditedData = await verifyAndCorrect(rawData, true);
  return { ...auditedData, theme: theme.split(' ')[0], liturgicalEvent: liturgicalContext?.event || null };
}

export function isConfigured() {
  return !!OPENROUTER_API_KEY();
}